[project]
name = "form-handling"
version = "1.0.0"
description = "Jac client application: form-handling"
entry-point = "main.jac"

[dependencies]

[dependencies.npm]
jac-client-node = "1.0.7"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client]
